name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Build imagen
      run: docker build -t mi-app .

    - name: Test simple
      run: echo "Pipeline funcionando "
