name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Build Docker
      run: docker build -t mi-app .

    - name: Test
      run: echo "CI/CD funcionando"
